#!/bin/bash
################################################################################
# Script to create or update a pnf object in A&AI

pnfType=${1,,};
. config

declare -A mapping=(
    [pnfId]=${pnfIdByType[$pnfType]}
)

echo "################################################################################";
echo "# delete PNF by name and resource-version from A&AI;"
echo "# Please note that the delete operation requires the current value of"
echo "# of the 'resource-version' attribute. This value is generated by A&AI only."
echo "# Therefore please use getPnf script to read the value and use it as "
echo "# second parameter of the deletePnf script."
echo

echo "       URI: "$aaiUri
echo "   SSL Key: "$aaiSslKey
echo "Key phrase: "$aaiSslKeyPsswd
echo "    App-id: "$aaiAppId

for key in "${!mapping[@]}"
do
  label=$spaces$key;
  label=${label:(-20)};
  echo "$label: ${mapping[$key]}";
  sequence="$sequence s/@$key@/${mapping[$key]}/g; "
done
echo;

# curl -i -k -E $crt --key $key -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-FromAppId: SDNR' -H 'X-TransactionId: 9999' $urlAai/aai/v8/network/pnfs
./jcurl.sh -v -k -p12 $aaiSslKey $aaiSslKeyPsswd -X DELETE -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-FromAppId: $aaiAppId' -H 'X-TransactionId: 9999' $aaiUri/network/pnfs/pnf/${pnfIdByType[$pnfType]}/?resource-version=$2"
